@startuml
skinparam monochrome true

object App {
    main
}

object Solution {
    name
    score
    makers
    takers
    matchers
}

object Solver {
    config
}

object Scorer {
    config
}

App -d- Solver
App -d- Solution
App -d- Scorer

Solver --r- Solution
Solution --r- Scorer

object Matcher {
    name
    maker
    taker
}

object Maker {
    name
}

object Taker {
    name
}

Solution o-d- Matcher
Matcher o-d- Maker
Matcher o-d- Taker

@enduml